### ISSUE TITLE
Partial PhoneCall value is passed as an argument to `endCall` method.

### ISSUE THREAD

**Issue by mocarz** [salesforce/scv-connector-base#6] opened 2021-09-14 12:59 UTC
When disconnecting a call participant using X button, `endCall` method is called with an argument that it not an instance of `PhoneCall`. Instead I get
```
{
    "callAttributes": {
        "participantType": "Initial_Caller"
    }
}
```
The method signature is `endCall(call: PhoneCall, agentStatus: string): Promise<HangupResult>`

I expect to get full `PhoneCall` instance, that would also include `callId`, which I care about.

I'm using `scv-connector-base` from this commit: `70b82e0e9eb3c925c3ccf6f53cc98f1ed0c2b6eb`.

**Comment by dlouvton** [comment] 2021-09-14 15:03
We expect you to store the active calls in a database (or localstorage, as done in the [demo connector](https://github.com/salesforce/demo-scv-connector), and then retrieve it. This call object just tells you that the call from the "Initial_Caller" is going to be ended.
The demo-connector code can give you more insight into how to implement your connector.

**Comment by estrudels** [comment] 2022-09-21 19:15
@mocarz Could you please consider **closing this issue** as you have been responded directly by the Salesforce Team with a solution/what is expected. Thank you!

**Comment by mocarz** [comment] 2022-09-22 05:41
@estrudels Even though I got the answer, I don't neccessary accept it. If `callId` and other fields aren't present

**Comment by mocarz** [comment] 2022-09-22 05:47
Please disregard the status change above, I closed it by a mistake by pressing enter unintentionally.

@estrudels Even though I got the answer, I don't necessary accept it. If `callId` and other fields aren't present, as required by the typescript interface, then at least the interface should be adjusted to match the data passed to the method.

**Comment by estrudels** [comment] 2022-09-22 12:16
@mocarz I understand your frustration, we are also integrating with Service Cloud Voice (SCV) and realize that the typings is a work in progress for the Salesforce Team around the SCV product

On our team we have to assume several interactions/states, along with implementing workarounds due to issues with the typings.

What @dlouvton said is still valid and is the approach we are using to implement SCV.

Hopefully the typings will get better/more accurate in future releases of SCV-Connector-App

Free community to keep your issue open, but really not sure you will get the exact change you desire

As 3rd party integrators we have to bend/flex to what Salesforce provides.

Please consider closing issue as doubt any action or change will come for your request as works as intended by SF

Thanks

**Comment by estrudels** [comment] 2022-09-22 20:34
Thoughts on this @vivektikoo-force ? Should this **Issue** being closed as **Works As Expected?**

**Comment by vivektikoo-force** [comment] 2022-09-22 21:11
Closing this as mentioned by @dlouvton,  for remove participant we pass the phone call object containing only necessary info

**Closed by vivektikoo-force** 2022-09-22 21:11 UTC
